### ISSUE TITLE
mrview:  stop resize of window when second tool pane is opened

### ISSUE THREAD

**Issue by draffelt** [jdtournier/mrtrix3#109]
Not sure what is causing this. The ODF pane seems to be one that resizes the window the most (if another pane is already open). It causes the window to be taller than 1080p, forcing a manual resize of the window.

**Comment by jdtournier** [comment]
Had a go at sorting this out. Seems to behave much better on my system - feedback welcome...

Still having strange issues that I can't figure out. Some of the tools can be shrunk to the extent that many of the elements start overlapping. The button shrink below their normal size, the tick boxes start bunching up and disappearing, etc. This is particularly obvious for the ODF tool. I have no idea why that is, the Qt basic layouts example does essentially the same thing (QGridLayout within a QGroupBox), and its contents don't get shrunk down to nothing. If anyone has any idea what might be causing this, please be my guest...

**Comment by draffelt** [comment]
Nice work. Looks great!  I appears the tools that don't shrink buttons, are those with large QListViews that absorb all the shrinkage.  What would your expected behaviour be for tools with many buttons (such as ODF and screen capture)? A scrollbar appears? or it stops the resize (like it used to).  Will have a quick look into it today.

**Comment by draffelt** [comment]
OK, so had a good crack at this with no luck. You can set a larger minimum size for a specific tool (e.g. 650 high is a good size minimum for screen capture), however for some reason when I open the tool it annoyingly resizes the window to be much larger (even though was already large enough to hold the tool).

**Comment by jdtournier** [comment]
Yes, infuriating, isn't it?

I think I now understand this crazy resize of the main window when adding tools. By default, tools get added in the docking area _below_ existing dock widgets. We then force the dock widget to tabify itself (which Qt doesn't make easy, as you well know), but by that stage, the main window has already decided that it needs to grow massively to host this new dock widget, and doesn't shrink back down when we force it into a tab. At least, that the only way I can make sense of this.

I also tried to force the dock widgets to only use tabs, with the `ForceTabbedDock` flag (can't remember exactly what it was), but that made no difference - clearly a bug. 

I'm guessing setting a minimum size on the dock widget means it'll try to honour that even if that forces child widgets to scrunch up in ridiculous ways. So that might explain that aspect of things. 

I think we might get somewhere by creating the tool as a floating dock widget, which would give it a chance to size itself appropriately _without_ affecting the main window, and then tabify after (if the config states that it should). Could even set that up with a QTimer or call processEvents() to make sure everything has been set up before tabifying...

Another option would be to figure out if there is a call that would give us the correct minimum size of the dock widget, once everything has been laid out. 

And who knows, maybe we'll need to combine both approaches...

**Comment by jdtournier** [comment]
Yup, as expected, needed both of these approaches... But the good news is it finally seems to behave as advertised. I'll close this issue, feel free to reopen if it doesn't work for you.
