### ISSUE TITLE
mrview: unwanted focus behaviour with anisotropic voxels

### ISSUE THREAD

**Issue by Lestropie** [jdtournier/mrtrix3#112]
Requires multiple clicks to move between slices.

**Comment by rtabbara** [comment]
I noticed that by default all the <code>slice_move_event</code>'s were incrementing by the minimal voxel dimension. This seemed strange to me because if you're moving through a plane where vox. dim > min, then passing 1 into <code>slice_move_event</code> will not actually move you by one voxel (?)

So for the case where we're snapped to image, I've changed to behaviour to use the corresponding vox. dim, while I've tentatively used the cube root of the product of the voxel sizes when we're not locked to the axes.

**Comment by jdtournier** [comment]
yes, I think your fix in ed27dfb is probably the only sensible way to go - this was more or less where the discussion had got to on the issue anyway. Thanks for pushing it over the line..
