### ISSUE TITLE
Display colourbar in overlay mode

### ISSUE THREAD

**Issue by draffelt** [jdtournier/mrtrix3#174]
We should reuse the colourbar menu from vector plot to also allow inversions, reset intensity and show/hide.

**Comment by rtabbara** [comment]
Ok, so this is done. Please check it out. A few things:

* Took the colourbar button logic Dave used in the Vector plot and put it in its own reusable <code>ColourMapButton</code> class.

* The button presents a menu listing of core/special(optional) colourmaps along with <code>Custom...</code> and <code>Random Colour</code> menu items that allow user-specified colourmaps.

* I found that the final colour used by the fragment shader when rendering user-specified maps to be a bit dull, so I punched up the final calculated colour by a scalar (see colourmap.cpp maps[]:Colour). Not sure whether this is kosher.

* I started moving away from relying on the colourmap index /maps[] to determine which colourmap is active. It's not a huge deal, but in the future we might want to think about introducing enum classes listing the different colourmap types available so that we can replace methods like <code>set_colourmap(1)</code> with <code>set_colourmap(ColourMap::Type::Hot)</code>. Right now, it seems there's too much reliance on the order of actions added to a menu matching the colourmap entries in ColourMap::maps[].

* Showing/hiding colour bar option in the window menu now affects other Tool colour bars as well. Not sure if people want this, but I thought it was consistent with the idea that toggling all annotations means wanting to clear the screen of everything.

@draffelt 

* Vector plot: I've removed the Colour by combo box options Manual/Random colour and have instead incorporated those within the ColourMapButton. 

* Also, similar to the default set of colourmaps, user-specified colours are now scaled by value and are no longer uniform. Let me know if that's ok otherwise I can revert that change. 

* Still need to fix up #172

**Comment by jdtournier** [comment]
Happy with all of this, sounds very sensible. Haven't tried it yet, I'll get round to that in a bit. 

As to using an enum for the colour maps, why not, if you find it easier to maintain. I went the way I did to make it easier to add colour maps later, but it's a pretty rare occurrence... Go for it is you think it's cleaner that way.

**Comment by jdtournier** [comment]
@rtabbara 

Finally had a play with your changes - all works great. Just one little niggle: any chance you could get the colourmap entries in the main view menu match those in your new ColourMapButton...? In particular having the Custom entry pop up a colour chooser, and if you could get the random colour entry to work as well, why not...?

I'm guessing this single-colour map will probably not be used a great deal, but it might be handy to overlay images pre/post registration in different colours for instance, by displaying the main image in one colour and the overlay in another. Otherwise, we could just remove that option from the main menu altogether - this can all be achieved using the overlay tool if need be...

**Comment by rtabbara** [comment]
@jdtournier Thanks for taking a look at it. Making the main view colourmap entries consistent with the other tools shouldn't be a problem, so I'll look to do that soon.

**Comment by thijsdhollander** [comment]
> I found that the final colour used by the fragment shader when rendering user-specified maps to be a bit dull, so I punched up the final calculated colour by a scalar (see colourmap.cpp maps[]:Colour). Not sure whether this is kosher.

@rtabbara : so, this factor of 2.7213 was deemed not so kosher in #259 , as it had unexpected consequences in the ROI overlay's colour.  I ended up taking out the factor for the time being, so #259 is not an issue anymore.
