### ISSUE TITLE
Progressbar error on Mac OS X

### ISSUE THREAD

**Issue by dchristiaens** [jdtournier/mrtrix3#184]
Hi Donald,

Since you merged pull request #181 yesterday, the progressbar does no longer clear the line on mac (tcsh). So instead of the regular behaviour, I get this:
```
tckgt: [  0%] loading data for image "../subj_2.mif"...tckgt: [  1%] loading data for image "../subj_2.mif"...tckgt: [  2%] loading data for image "../subj_2.mif"...
```
and so on (without newlines in between).

Any idea what could be going on?

**Comment by jdtournier** [comment]
Darn. Could that be due to the terminal being too narrow...?

**Comment by dchristiaens** [comment]
I doubt it, it's 150 characters wide.

**Comment by jdtournier** [comment]
Right... I'll look into it.

**Comment by dchristiaens** [comment]
Thanks. Same problem on bash, by the way.

**Comment by jdtournier** [comment]
I don't have access to a Mac at the moment, it'll be a while before I can look into this myself. In the meantime, the only way I can explain this behaviour is if the detection of redirection of stderr is getting it wrong. Any chance you could add this line:

    VAR (stderr_to_file);

in file `lib/app.cpp`, line 517? If you rebuild and run, and it reports the value to be non-zero, then we'll know what the problem is...

**Comment by dchristiaens** [comment]
Yes, `[lib/app.cpp: 517]: stderr_to_file = 1`

**Comment by jdtournier** [comment]
OK, I just pushed branch `stderr_redirection_on_macosx` with a possible fix. Do you mind giving it a shot, see if that works...?

**Comment by dchristiaens** [comment]
Sorry, the error persists...
```dwi2fod: [  0%] uncompressing image "dwi.nii.gz"...dwi2fod: [  0%] uncompressing image "dwi.nii.gz"...dwi2fod: [  1%] uncompressing image "dwi.nii.gz"...dwi2fod: [  2%] uncompressing image "dwi.nii.gz"...dwi2fod: [  3%] uncompressing image "dwi.nii.gz"...dwi2fod: [  4%] uncompressing image "dwi.nii.gz"...dwi2fod: [  5%] uncompressing image "dwi.nii.gz"...```

**Comment by jdtournier** [comment]
I'm a bit stumped by this... According to the [Mac Developer Library](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/lseek.2.html), this really ought to fail outright:

> Upon successful completion, lseek() returns the resulting offset location as measured in bytes from the beginning of the file.  Otherwise, a value of -1 is returned and errno is set to indicate the error.

I thought this might be failing to report an error since seeking by zero from the current position is technically a no-op, so it might have returned success simply because there was nothing to do, but it seems not be the case: this last change requested a seek back and forth by one byte, it really should have failed... 

There was a suggestion in an ancient post that this could be due to failing to include `unistd.h`, causing the compiler to assume an `int` type in the return code (rather than `off_t`), but this only applies to BigEndian PPC systems, and I don't think there's many of them left... Just to check this, I've updated the `stderr_redirection_on_macosx` branch to include it, but I don't think it'll make any difference - we compile with `-Wall`, which should have at least produced a warning... Please try it in any case, just to rule out the possibility. 

In the meantime, I think the only fix will be to test whether the file is a regular file or not - I'll look into that on Linux, see if I can get it to work.

**Comment by jdtournier** [comment]
OK, it's easy enough to figure out whether stderr points to a regular file, and it seems to work just fine on Linux. I just pushed that change to the `stderr_redirection_on_macosx` branch, see if that works on MacOSX...

**Comment by dchristiaens** [comment]
Yes, your latest commit 0be9a043d4ed58edec0937d7ac276ade53ac474e fixes the issue. Did someone test it on Windows too?

**Comment by jdtournier** [comment]
Good to hear. Not tested on Windows so far, that I know. I'll merge this one anyway and test it on Windows tomorrow - I don't anticipate any particular problems there.

**Comment by dchristiaens** [comment]
Good. Thanks for fixing!

**Comment by Lestropie** [comment]
Windows appears to be happy.

**Comment by jdtournier** [comment]
Good to hear, thanks!
