### ISSUE TITLE
RAS coordinates discrepency between mrtrix 2 & 3

### ISSUE THREAD

**Issue by zewam74** [jdtournier/mrtrix3#186]
Hi,

I just noticed a slight difference between the RAS coordinates measured with mrtrix 2, mrtrix 3, freeview and SPM viewer.

If I open the exact same image (.nii format) and place the cursor on the same voxel, I have different RAS coordinates. Actually, SPM viewer and freeview returned the same RAS coordinates (talking into account the [1 1 1] matlab origin), whereas mrview (package mrtrix 2) and mrview (package mrtrix 3) returned 2 different RAS coordinates.

Please find enclosed 4 screen captures of my observations. The first image are the coordinates provided by freeview, the second by spm viewer, image 3 by mrview 2 and image 4 by mrview 3.
![freeview](https://cloud.githubusercontent.com/assets/7534242/6805659/74d5fb62-d244-11e4-9e5f-dc531d3df106.png)
![spm](https://cloud.githubusercontent.com/assets/7534242/6805667/800eb564-d244-11e4-8874-bb7b26369403.png)
![mrtrix2](https://cloud.githubusercontent.com/assets/7534242/6805671/83141d80-d244-11e4-9b8b-2bfada08b64c.png)
![mrtrix3](https://cloud.githubusercontent.com/assets/7534242/6805674/85156e0e-d244-11e4-8f21-fdb5dd6ec235.png)

Also notice that the RAS coordinates change if I convert the .nii image to .mif. In this case, mrview (v3) returns the RAS coordinates : 11, 11.32, 29.18 (for the same voxel 76, 113, 92).

Do you have an idea how is that ?

Thanks !

**Comment by jdtournier** [comment]
It seems to me the main differences you're highlighting are due to one of two things:

- both versions of MRtrix index voxels from zero, whereas I'm guessing the other packages would index them from one (especially SPM, being MatLab-based). That seems to explain the bulk of the differences.

- mrview in both version of MRtrix allow you to place the cursor at an arbitrary point in 3D space - not necessarily in step with the image grid, or locked to the voxel centres. The voxel index in the display is however rounded to the nearest voxel. Given that you're in pretty much the same location in all cases (within ½mm or so), I don't think there's any problem with what you're showing.

Does this explain the differences?

**Comment by zewam74** [comment]
I tested your second point with mrview full screen and indeed, that may totally explain the slight differences I observed.

Thank you.

**Comment by jdtournier** [comment]
No problem!
Cheers,
Donald.
