### ISSUE TITLE
please use "#!/usr/bin/env python" instead of "#!/usr/bin/python"

### ISSUE THREAD

**Issue by samfux84** [jdtournier/mrtrix3#217]
Dear MRtrix3 developers,

I recently installed MRtrix3 on a HPC cluster. HPC Clusters usually run a very old OS (in my case it is CentOS 6.5). Therefore the standard Python interpreter shipped with the OS is version 2.6. Usually newer Python versions are installed in non-standart locations.

By using  "#!/usr/bin/env python" instead of "#!/usr/bin/python" it will take the newer interpreter if available (if the Python module is loaded) and fall back to /usr/bin/python if no newer interpreter is available.

In order to get MRtrix3 installed, I had apply this change in all Python scripts manually before being able to compile the software. Please consider this for future releases of MRtrix3.

Thank you very much and Best regards

Samuel Fux

**Comment by jdtournier** [comment]
Yes, we should probably do this, it's the recommended way these days. I'll sort this out in a minute.

By the way, you don't need to edit the scripts to run them, you can always invoke the interpreter directly, passing the script as an argument. Though I agree it's not as neat as the change you're suggesting...

**Comment by jdtournier** [comment]
@Lestropie , @draffelt : I notice pretty much all your scripts in the `scripts/` folder are not compatible with Python 3. You probably should try to fix that - it's not that hard, although the whole bytes vs. strings, encode/decode thing is admittedly a bit irritating...

In the meantime, I'll update `build` & `configure` to use `#!/usr/bin/env python`, since it's the [recommended approach](https://docs.python.org/2/tutorial/appendix.html#executable-python-scripts) anyway. And I'll update your scripts to use `#!/usr/bin/env python2` for now...
